import type { Metadata } from "next";
import "./globals.css";
import { monument, satoshi } from "@/lib/fonts";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="group">
      <body className={`bg-[#000000] font-satoshi p-0 m-0 box-border ${satoshi.variable} ${monument.variable}`}>
        <main className="flex min-h-screen flex-col">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
